# Default values for lava-gitlab-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

loglevel: "info"
# Lava can struggle with a lot of parallel request so minimize these to
# something reasonably low
max_concurrent_requests: 4

gitlab:
  url: https://your.gitlab.server.org
  #Set the runner token for a first deployment. It's inherited on later
  #deployements
  # token: 12345

image:
  repository: ghcr.io/collabora/lava-gitlab-runner
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.3.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
  runAsGroup: 1001

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
